// Standard and robust QR Code Generator using the standard 'qrcode' library.
// This allows us to generate real, spec-compliant QR Codes that any standard
// scanner (like jsQR used in our app, or standard mobile device cameras) can decode instantly.

import QRCode from "qrcode";

export function getQrGrid(text: string): boolean[][] {
  const matrixSize = 25; // Keep Version 2 (25x25) as expected by QRGenerator PDF drawing
  try {
    // Generate a standardized Version 2 QR code with Low Error Correction
    const qr = QRCode.create(text, { version: 2, errorCorrectionLevel: "L" });
    const size = qr.modules.size;
    
    const grid: boolean[][] = Array(matrixSize).fill(null).map(() => Array(matrixSize).fill(false));
    
    for (let r = 0; r < matrixSize; r++) {
      for (let c = 0; c < matrixSize; c++) {
        if (r < size && c < size) {
          if (typeof qr.modules.get === "function") {
            grid[r][c] = !!qr.modules.get(r, c);
          } else {
            grid[r][c] = !!qr.modules.data[r * size + c];
          }
        }
      }
    }
    return grid;
  } catch (err) {
    console.error("Failed to generate standard QR Code grid using npm library. Checking version 2 constraints.", err);
    
    try {
      // In case of any constraint error, auto-select version and map it back safely to 25x25
      const qr = QRCode.create(text, { errorCorrectionLevel: "L" });
      const size = qr.modules.size;
      const grid: boolean[][] = Array(matrixSize).fill(null).map(() => Array(matrixSize).fill(false));
      
      for (let r = 0; r < matrixSize; r++) {
        for (let c = 0; c < matrixSize; c++) {
          const mappedR = Math.floor((r / matrixSize) * size);
          const mappedC = Math.floor((c / matrixSize) * size);
          if (typeof qr.modules.get === "function") {
            grid[r][c] = !!qr.modules.get(mappedR, mappedC);
          } else {
            grid[r][c] = !!qr.modules.data[mappedR * size + mappedC];
          }
        }
      }
      return grid;
    } catch (fallbackErr) {
      console.error("Critical fallback failed: ", fallbackErr);
      return Array(matrixSize).fill(null).map(() => Array(matrixSize).fill(false));
    }
  }
}

export function generateQrSvg(text: string, size = 150): string {
  // To keep 100% parity with PDF rendering and grid layouts, we construct the SVG
  // using the exact same boolean grid generated by getQrGrid!
  const matrixSize = 25;
  const grid = getQrGrid(text);
  
  // Build clean, sharp SVG path
  const cellSize = size / matrixSize;
  let path = "";
  for (let r = 0; r < matrixSize; r++) {
    for (let c = 0; c < matrixSize; c++) {
      if (grid[r][c]) {
        const x = c * cellSize;
        const y = r * cellSize;
        path += `M${x.toFixed(1)},${y.toFixed(1)}h${cellSize.toFixed(1)}v${cellSize.toFixed(1)}h-${cellSize.toFixed(1)}z `;
      }
    }
  }
  
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
    <rect width="100%" height="100%" fill="#ffffff" />
    <path d="${path}" fill="#1e293b" />
  </svg>`;
}

export function decodeQrContent(text: string): string | null {
  if (text.startsWith("hijaiyah:")) {
    return text.replace("hijaiyah:", "");
  }
  return null;
}
